package proyectologica;
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 3;
  public static final int CATNAME = 12;
  public static final int SELECT = 2;
  public static final int EQUAL = 7;
  public static final int CATTZ = 16;
  public static final int SEMI = 11;
  public static final int GREATER = 6;
  public static final int COUNTRIESDB = 20;
  public static final int CATCOUNTRY = 13;
  public static final int WITH = 5;
  public static final int OF = 4;
  public static final int EVERYCAT = 19;
  public static final int THANTOCONN = 9;
  public static final int CATGOV = 17;
  public static final int LOWER = 8;
  public static final int NUMBER = 22;
  public static final int EOF = 0;
  public static final int CATLANGS = 15;
  public static final int CATPOP = 14;
  public static final int CATSIZE = 18;
  public static final int error = 1;
  public static final int TEXT = 21;
  public static final int INCLUDING = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SELECT",
  "AND",
  "OF",
  "WITH",
  "GREATER",
  "EQUAL",
  "LOWER",
  "THANTOCONN",
  "INCLUDING",
  "SEMI",
  "CATNAME",
  "CATCOUNTRY",
  "CATPOP",
  "CATLANGS",
  "CATTZ",
  "CATGOV",
  "CATSIZE",
  "EVERYCAT",
  "COUNTRIESDB",
  "TEXT",
  "NUMBER"
  };
}

